[global]
	target = "~/.local/bin"
	upgrade_only = true

["zyedidia/eget"]

["zyedidia/micro"]
	asset_filters = [ "static", ".tar.gz" , "^sha" ]

["ip7z/7zip"]
	# Currently not working as 7zip packages use xz filters unsupported by eget/xz go library
	#file = "7zzs"
	#target = "~/.local/bin/7z"
	download_only = true

["sharkdp/bat"]
	asset_filters = [ "gnu", ".tar.gz" ]

["BurntSushi/ripgrep"]

["sharkdp/fd"]
	asset_filters = [ "gnu" ]

["sharkdp/hyperfine"]
	asset_filters = [ "gnu" ]

["ajeetdsouza/zoxide"]

["neovim/neovim"]
	asset_filters = [ "x86_64" ]
	target = "~/.local/bin/nvim"

["konosubakonoakua/ncdu-zig"]
	target = "~/.local/bin/ncdu"

["eza-community/eza"]
	asset_filters = [ "gnu", ".tar.gz" ]

["starship/starship"]
	asset_filters = [ "gnu" ]

["Byron/dua-cli"]

["doy/rbw"]

["twpayne/chezmoi"]
	asset_filters = [ "glibc", ".tar.gz" ]

["scop/bash-completion"]
	# Needs manual intervention to install, as its a bash script with a subfolder containing completions
	download_only = true
	asset_filters = [ ".tar.xz" ]

 ["srevinsaju/Firefox-Appimage"]
    target = "~/.local/bin/firefox"
	tag = "firefox"
	asset_filters = [ ".AppImage", "^zsync" ]

["BtbN/FFmpeg-Builds"]
	asset_filters = [ "^lgpl", "shared", "master", ".tar.xz" ]
	download_only = true # Shared libraries aren't extracted correctly, need to do in post install script

["romkatv/zsh-bin"]
	asset_filters = [ "^asc" ]
#	all = true
	file = "bin/zsh"

["xyproto/gendesk"]
	asset_filters = [ "static" ]

["neovide/neovide"]

["valicm/VSCode-AppImage"]
	asset_filters = [ ".AppImage", "^zsync" ]
	target = "~/.local/bin/code"

#["containers/podman"]
#	target = "~/.local/bin/podman"

#["89luca89/lilipod"]
#	target = "~/.local/bin/lilipod"

["sharkdp/numbat"]
	asset_filters = [ "gnu", ".tar.gz" ]

["sharkdp/hexyl"]
	asset_filters = [ "gnu", ".tar.gz" ]

["chmln/sd"]
	asset_filters = [ "gnu", ".tar.gz" ]

["bootandy/dust"]
	asset_filters = [ "gnu", ".tar.gz" ]

["tealdeer-rs/tealdeer"]

["nushell/nushell"]
	asset_filters = [ "musl", ".tar.gz" ]
	all = true

# TODO: Change to no extract so I can setup shared librarys and terminfo etc, as well as get kitten binary
["kovidgoyal/kitty"]
	asset_filters = [ "^sig", "^kitten", "x86_64" ]

